import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "../../components/Header/Navbar";
import Provider  from "./providers";
import Footer from "../../components/Footer/Footer";
import classNames from "classnames";
import {cookies} from "next/headers";
import Template from "@/app/(site)/template";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function getTheme() {
  const cookieStore = cookies();
  const themeCookie = cookieStore.get("theme");
  const theme = themeCookie ? themeCookie.value : "dark";
  return theme;
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const theme = getTheme() as string;
  return (
    <html lang="en"
          className={classNames(inter.className, 'scroll-smooth',theme)}
          style={{ colorScheme: theme }}
          suppressHydrationWarning
      >
      <body>
        <Provider>
          <Navbar />
          <Template>
          {children}
          </Template>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
